title: ""
description: "A comprehensive guide to design patterns, best practices, and real-world examples."
author: "@gvatsal60"
exclude:
  - "*.cpp"
  - "*.h"
  - "*.hpp"
  - "*.c++"
  - "*.cc"
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
