# Site Settings
title: ""
description: "A comprehensive guide to design patterns, best practices, and real-world examples."
author: "@gvatsal60"
baseurl: "design_patterns" # Leave as '/' unless you're deploying in a sub-folder

# Theme settings
theme:
  name: "minimal-mistakes-jekyll"
  logo: "" # Optional logo path (can be customized)
  dark_mode: true # Enable dark mode (optional)

# Navigation settings
navigation:
  - Home: "/"
# - Introduction: "/introduction/"
# - Design Patterns: "/patterns/"
# - Blog: "/blog/"
# - Contact: "/contact/"

# Enable the search feature
search:
  enabled: true

# Enable table of contents for markdown pages
toc:
  enabled: true

# Exclude files
exclude:
  - "*.cpp"
  - "*.h"
  - "*.hpp"
  - "*.c++"
  - "*.cc"

# Plugins (optional)
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Relative links configuration
relative_links:
  enabled: true
  collections: true

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM # GitHub Flavored Markdown

# Permalinks (define how URLs should look for pages)
permalink: /:categories/:title/

# Default layout for posts and pages
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "@gvatsal60"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Footer
footer:
  text: "A comprehensive guide to design patterns, best practices, and real-world examples."

# Analytics (optional)
# google_analytics: "UA-XXXXXXXX-X"

# Social Links
social:
  github: "https://github.com/gvatsal60/"
  linkedin: "https://www.linkedin.com/in/gvatsal60/"
